<?php

namespace App\Helpers;

class CountryHelper
{
    // List of all countries (ISO 3166-1 alpha 1)
    private static array $countries = [
        'AF',
        'AX',
        'AL',
        'DZ',
        'AS',
        'VI',
        'AD',
        'AO',
        'AI',
        'AQ',
        'AG',
        'AR',
        'AM',
        'AW',
        'AU',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BT',
        'BO',
        'BA',
        'BW',
        'BV',
        'BR',
        'IO',
        'VG',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CA',
        'CF',
        'CL',
        'CN',
        'CX',
        'CC',
        'CO',
        'KM',
        'CG',
        'CD',
        'CK',
        'CR',
        'CU',
        'CY',
        'DK',
        'DJ',
        'DM',
        'DO',
        'DE',
        'EC',
        'EG',
        'SV',
        'GQ',
        'ER',
        'EE',
        'ET',
        'FO',
        'FK',
        'FJ',
        'PH',
        'FI',
        'FR',
        'GF',
        'PF',
        'TF',
        'GA',
        'GM',
        'GE',
        'GH',
        'GI',
        'GD',
        'GR',
        'GL',
        'GP',
        'GU',
        'GT',
        'GG',
        'GN',
        'GW',
        'GY',
        'HT',
        'HM',
        'HN',
        'HU',
        'HK',
        'IE',
        'IS',
        'IN',
        'ID',
        'IQ',
        'IR',
        'IM',
        'IL',
        'IT',
        'CI',
        'JM',
        'JP',
        'YE',
        'JE',
        'JO',
        'KY',
        'CV',
        'CM',
        'KZ',
        'KE',
        'KG',
        'KI',
        'UM',
        'KW',
        'HR',
        'LA',
        'LS',
        'LV',
        'LB',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MK',
        'MG',
        'MW',
        'MV',
        'MY',
        'ML',
        'MT',
        'MA',
        'MH',
        'MQ',
        'MR',
        'MU',
        'YT',
        'MX',
        'FM',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MZ',
        'MM',
        'NA',
        'NR',
        'NL',
        'AN',
        'NP',
        'NI',
        'NC',
        'NZ',
        'NE',
        'NG',
        'NU',
        'KP',
        'MP',
        'NO',
        'NF',
        'UG',
        'UA',
        'UZ',
        'OM',
        'TL',
        'AT',
        'PK',
        'PW',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PN',
        'PL',
        'PT',
        'PR',
        'QA',
        'RO',
        'RU',
        'RW',
        'RE',
        'KN',
        'LC',
        'VC',
        'BL',
        'PM',
        'SB',
        'WS',
        'SM',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SH',
        'MF',
        'SI',
        'SK',
        'SD',
        'SO',
        'ES',
        'SJ',
        'LK',
        'SR',
        'SZ',
        'SY',
        'TJ',
        'TW',
        'TZ',
        'TH',
        'TG',
        'TK',
        'TO',
        'TT',
        'TD',
        'CZ',
        'TN',
        'TR',
        'TM',
        'TC',
        'TV',
        'UY',
        'VU',
        'VA',
        'VE',
        'GB',
        'AE',
        'US',
        'VN',
        'WF',
        'EH',
        'BY',
        'ZM',
        'ZW',
        'ZA',
        'GS',
        'KR',
        'SE',
        'CH',
    ];

    // List of all countries currently in the EU (ISO 3166-1 alpha 1)
    private static array $countriesInEU = [
        'BE',
        'BG',
        'CZ',
        'DK',
        'DE',
        'EE',
        'IE',
        'GR',
        'ES',
        'FR',
        'HR',
        'IT',
        'CY',
        'LV',
        'LT',
        'LU',
        'HU',
        'MT',
        'NL',
        'AT',
        'PL',
        'PT',
        'RO',
        'SI',
        'SK',
        'FI',
        'SE',
    ];

    public static function getDropDownListByIsoCode(bool $withBlankOption = false, bool $outsideEu = true): array
    {
        $countries = $outsideEu ? self::$countries : self::$countriesInEU;
        $dropDownList = [];
        foreach ($countries as $countryCode) {
            $dropDownList[$countryCode] = self::getCountryNameByCode($countryCode);
        }
        if ($withBlankOption) {
            $dropDownList[null] = null;
        }
        asort($dropDownList);

        return $dropDownList;
    }

    public static function getCountryNameByCode(string $countryCode): ?string
    {
        if (!in_array($countryCode, self::$countries)) {
            return $countryCode;
        }

        return __('country.' . strtoupper($countryCode));
    }

    public static function isCountryByCodeInEU(string $countryCode): bool
    {
        return in_array(strtoupper($countryCode), self::$countriesInEU);
    }

    public static function getEuCountriesIsoCodes(): array
    {
        return self::$countriesInEU;
    }

    public static function isCountryTheNetherlandsByCode(string $countryCode): bool
    {
        return $countryCode === 'NL';
    }
}
